FROM php:8.2-apache

COPY . /var/www/html/

ENV PORT 10000

RUN sed -ri "s/Listen 80/Listen ${PORT}/" /etc/apache2/ports.conf \
 && sed -ri "s/VirtualHost \*:80/VirtualHost *:${PORT}/" /etc/apache2/sites-available/000-default.conf

EXPOSE 10000

CMD ["apache2-foreground"]
